server:
  port: 0

spring:
  profiles:
    include: kafka
  application:
    name: deployment-service
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"


producers:
  topics:
    create-compute:
      name: create-compute
    rebuild-compute:
      name: rebuild-compute
    delete-project-exception:
      name: delete-project-exception
    delete-database:
      name: delete-database
    update-domain-name-exception:
      name: update-domain-name-exception
    command-deployment-status:
      name : command-deployment-status
    create-database:
      name : create-database

consumers:
  topics:
    create-hosting:
      name: create-hosting
    update-deployment-status:
      name: update-deployment-status
    delete-deployment:
      name: delete-deployment
    update-database-status:
      name : update-database-status
    update-domain-name:
      name: update-domain-name

  group-id:
    save-hosting:
      name: save_hosting
    update-deployment-status:
      name: update_deployment_status
    update-database-status:
      name : update-database-status
    delete-deployment:
      name: project_deletion_initiated
    update-hosting-status:
      name: update_hosting_status