spring:
  config:
    import: configserver:http://localhost:8888
    name: deployment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

hosts:
  logstash: localhost

subdomain:
  endpoint: http://localhost:8001