spring:
  config:
    import: optional:configserver:http://config-server:8888
    name: compute-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

hosts:
  logstash: logstash