server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/user/**
          filters:
            - AuthenticationHeaderFilter

        - id: project-service-api
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/v1/project/**
          filters:
            - AuthenticationHeaderFilter

        - id: project-service-feign
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/feign/project/**
          filters:
            - AuthenticationHeaderFilter

        - id: project-service-elastic
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/v1/log/**
          filters:
            - AuthenticationHeaderFilter

        - id: compute-service-ws
          uri: lb:ws://COMPUTE-SERVICE
          predicates:
            - Path=/ws/**

        - id: compute-service-api
          uri: lb://COMPUTE-SERVICE
          predicates:
            - Path=/v1/compute/**
          filters:
            - AuthenticationHeaderFilter

        - id: deployment-service-api
          uri: lb://DEPLOYMENT-SERVICE
          predicates:
            - Path=/v1/deployment/**
          filters:
            - AuthenticationHeaderFilter

        - id: deployment-service-feign
          uri: lb://DEPLOYMENT-SERVICE
          predicates:
            - Path=/feign/deployment/**
          filters:
            - AuthenticationHeaderFilter

        - id: notification-service-api
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/v1/notification/**

        - id: deployment-service-webhook
          uri: lb://DEPLOYMENT-SERVICE
          predicates:
            - Path=/webhook/deployment/**