server:
  port: 0

spring:
  profiles:
    include: kafka
  application:
    name: project-service
  elasticsearch:
    uris: 34.64.227.45:9200

producers:
  topics:
    delete-deployment:
      name: delete-deployment
    update-domain-name:
      name: update-domain-name

consumers:
  topics:
    delete-project-exception:
      name: delete-project-exception
    update-domain-name-exception:
      name: update-domain-name-exception

  group-id:
    project-deletion-group:
      name: project_deletion_group
    update-hosting-status:
      name: update_hosting_status



